spring:
  application:
    name: eureka-server
server:
  port: 7000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #表示是否将自己注册到eureka server，默认为true
    fetch-registry: false #表示是否从eureka server获取注册信息，默认为true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#        http://${eureka.instance.hostname}:${server.port}/eureka/
